# Generated by Django 6.1 on 2026-09-08 10:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('ACADEMIC', 'Academic Performance / Grades'), ('ATTENDANCE', 'Attendance / Leave Notice'), ('BEHAVIOR', 'Conduct & Well-being'), ('FINANCE', 'Fees & Tuition Inquiry'), ('GENERAL', 'General Inquiry')], default='GENERAL', max_length=30)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_threads', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(help_text='Users participating in this conversation', related_name='conversation_threads', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(help_text='Student associated with this inquiry', on_delete=django.db.models.deletion.CASCADE, related_name='conversation_threads', to='students.student')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolAnnouncement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('target_audience', models.CharField(choices=[('ALL', 'Everyone (All Roles)'), ('PARENTS', 'Parents & Guardians Only'), ('TEACHERS', 'Faculty & Teachers Only'), ('STUDENTS', 'Students Only')], default='ALL', max_length=20)),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('IMPORTANT', 'Important'), ('URGENT', 'Urgent Notice')], default='NORMAL', max_length=20)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreadMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_by', models.ManyToManyField(blank=True, related_name='read_thread_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_thread_messages', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communications.conversationthread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversationthread',
            index=models.Index(fields=['status', '-updated_at'], name='communicati_status_f69337_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationthread',
            index=models.Index(fields=['student'], name='communicati_student_f06a30_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationthread',
            index=models.Index(fields=['category'], name='communicati_categor_443ec5_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolannouncement',
            index=models.Index(fields=['target_audience', 'is_published', '-created_at'], name='communicati_target__4a2e82_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolannouncement',
            index=models.Index(fields=['priority'], name='communicati_priorit_1eb63b_idx'),
        ),
        migrations.AddIndex(
            model_name='threadmessage',
            index=models.Index(fields=['thread', 'created_at'], name='communicati_thread__4088da_idx'),
        ),
    ]
