# Generated by Django 6.1 on 2026-09-02 08:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('room_number', models.CharField(max_length=50, unique=True)),
                ('building', models.CharField(blank=True, default='', max_length=100)),
                ('capacity', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['building', 'room_number'],
            },
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exam_type', models.CharField(choices=[('MIDTERM', 'Midterm'), ('FINAL', 'Final'), ('QUIZ', 'Quiz'), ('PRACTICAL', 'Practical')], default='MIDTERM', max_length=20)),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_schedules', to='academics.academicyear')),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='academics.classsection')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_schedules', to='scheduling.room')),
            ],
            options={
                'ordering': ['exam_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('term', models.CharField(default='Term 1', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_schedules', to='academics.academicyear')),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='academics.classsection')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_schedules', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_schedules', to='scheduling.room')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
    ]
