# Generated by Django 6.1 on 2026-08-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_studentprofile_user'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentprofile',
            name='students',
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='parents', to='students.student'),
        ),
    ]
