# Generated by Django 6.1 on 2026-09-02 14:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('FEE_DUE', 'Fee Due Notice'), ('FEE_PAID', 'Fee Paid Confirmation'), ('CLASS_SCHEDULE_CHANGED', 'Class Schedule Changed'), ('EXAM_ANNOUNCED', 'Exam Announced'), ('GRADE_POSTED', 'Grade Posted'), ('ATTENDANCE_ALERT', 'Attendance Alert'), ('TEACHER_MESSAGE', 'Teacher Message'), ('SCHOOL_ANNOUNCEMENT', 'School Announcement'), ('SYSTEM_ALERT', 'System Alert')], default='SYSTEM_ALERT', max_length=40)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('recipient_role', models.CharField(blank=True, default='', help_text='Cached role for fast role-based query filtering', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(help_text='The user receiving this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_student', models.ForeignKey(blank=True, help_text='Student associated with this alert (crucial for parent view filtering)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='students.student')),
                ('sender', models.ForeignKey(blank=True, help_text='The staff/teacher author of this notification (null for automated system notices)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx'), models.Index(fields=['recipient_role', '-created_at'], name='notificatio_recipie_1d360f_idx'), models.Index(fields=['related_student'], name='notificatio_related_b18328_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx')],
            },
        ),
    ]
